# GitHub Labels Configuration for AWS Organization Development
# Apply these labels using GitHub CLI: gh label create "name" -d "description" -c "color"
# Or import via GitHub's UI: Settings → Labels → Import

# ===== TYPE LABELS =====
- name: type:feature
  color: '0E8A16'
  description: New feature or enhancement

- name: type:bug
  color: 'D73A4A'
  description: Something isn't working

- name: type:infrastructure
  color: '5319E7'
  description: Infrastructure changes (IaC, AWS resources)

- name: type:security
  color: 'B60205'
  description: Security-related changes or vulnerabilities

- name: type:documentation
  color: '0075CA'
  description: Documentation updates or improvements

- name: type:refactor
  color: 'FBCA04'
  description: Code refactoring without functional changes

- name: type:test
  color: '1D76DB'
  description: Testing-related changes

- name: type:maintenance
  color: 'FEF2C0'
  description: Routine maintenance tasks

- name: type:ci-cd
  color: '0052CC'
  description: CI/CD pipeline changes

- name: type:monitoring
  color: 'C5DEF5'
  description: Monitoring, logging, or observability

# ===== AWS SERVICE LABELS =====
- name: aws:iam
  color: 'FF9900'
  description: AWS IAM (Identity and Access Management)

- name: aws:vpc
  color: 'FF9900'
  description: AWS VPC and networking

- name: aws:ec2
  color: 'FF9900'
  description: AWS EC2 instances

- name: aws:ecs
  color: 'FF9900'
  description: AWS ECS/Fargate

- name: aws:lambda
  color: 'FF9900'
  description: AWS Lambda functions

- name: aws:s3
  color: 'FF9900'
  description: AWS S3 storage

- name: aws:rds
  color: 'FF9900'
  description: AWS RDS databases

- name: aws:dynamodb
  color: 'FF9900'
  description: AWS DynamoDB

- name: aws:cloudwatch
  color: 'FF9900'
  description: AWS CloudWatch monitoring

- name: aws:cloudfront
  color: 'FF9900'
  description: AWS CloudFront CDN

- name: aws:route53
  color: 'FF9900'
  description: AWS Route53 DNS

- name: aws:alb
  color: 'FF9900'
  description: AWS Application Load Balancer

- name: aws:nlb
  color: 'FF9900'
  description: AWS Network Load Balancer

- name: aws:elasticache
  color: 'FF9900'
  description: AWS ElastiCache (Redis/Memcached)

- name: aws:sqs
  color: 'FF9900'
  description: AWS SQS queues

- name: aws:sns
  color: 'FF9900'
  description: AWS SNS notifications

- name: aws:kinesis
  color: 'FF9900'
  description: AWS Kinesis streams

- name: aws:secrets-manager
  color: 'FF9900'
  description: AWS Secrets Manager

- name: aws:kms
  color: 'FF9900'
  description: AWS KMS encryption

- name: aws:organizations
  color: 'FF9900'
  description: AWS Organizations

- name: aws:control-tower
  color: 'FF9900'
  description: AWS Control Tower

- name: aws:security-hub
  color: 'FF9900'
  description: AWS Security Hub

- name: aws:guardduty
  color: 'FF9900'
  description: AWS GuardDuty

- name: aws:config
  color: 'FF9900'
  description: AWS Config

- name: aws:cloudtrail
  color: 'FF9900'
  description: AWS CloudTrail

- name: aws:xray
  color: 'FF9900'
  description: AWS X-Ray tracing

# ===== PRIORITY LABELS =====
- name: priority:critical
  color: 'B60205'
  description: P0 - Critical priority, production down

- name: priority:high
  color: 'D93F0B'
  description: P1 - High priority, important feature

- name: priority:medium
  color: 'FBCA04'
  description: P2 - Medium priority, standard work

- name: priority:low
  color: 'FEF2C0'
  description: P3 - Low priority, nice to have

# ===== ENVIRONMENT LABELS =====
- name: env:dev
  color: '1D76DB'
  description: Development environment

- name: env:staging
  color: '0E8A16'
  description: Staging environment

- name: env:prod
  color: 'B60205'
  description: Production environment

- name: env:all
  color: '5319E7'
  description: All environments

# ===== STATUS LABELS =====
- name: status:blocked
  color: 'D73A4A'
  description: Blocked by dependency or external factor

- name: status:in-progress
  color: '0E8A16'
  description: Currently being worked on

- name: status:needs-review
  color: 'FBCA04'
  description: Ready for review

- name: status:needs-testing
  color: 'FF9900'
  description: Needs testing or QA

- name: status:on-hold
  color: 'FEF2C0'
  description: On hold, not currently active

- name: needs-triage
  color: 'E99695'
  description: Needs initial triage and prioritization

# ===== SIZE/EFFORT LABELS =====
- name: size:xs
  color: 'C2E0C6'
  description: Extra small - < 2 hours

- name: size:s
  color: 'C2E0C6'
  description: Small - 2-4 hours

- name: size:m
  color: 'BFDADC'
  description: Medium - 1-2 days

- name: size:l
  color: 'F9D0C4'
  description: Large - 3-5 days

- name: size:xl
  color: 'F9D0C4'
  description: Extra large - 1+ weeks

# ===== COMPLIANCE LABELS =====
- name: compliance:soc2
  color: '5319E7'
  description: SOC 2 compliance related

- name: compliance:iso27001
  color: '5319E7'
  description: ISO 27001 compliance related

- name: compliance:pci-dss
  color: '5319E7'
  description: PCI DSS compliance related

- name: compliance:hipaa
  color: '5319E7'
  description: HIPAA compliance related

- name: compliance:gdpr
  color: '5319E7'
  description: GDPR compliance related

# ===== COST LABELS =====
- name: cost:high
  color: 'D93F0B'
  description: High cost impact (> $1000/month)

- name: cost:medium
  color: 'FBCA04'
  description: Medium cost impact ($100-$1000/month)

- name: cost:low
  color: 'C5DEF5'
  description: Low cost impact (< $100/month)

- name: cost:optimization
  color: '0E8A16'
  description: Cost optimization opportunity

# ===== IMPACT LABELS =====
- name: impact:high
  color: 'D93F0B'
  description: High business or user impact

- name: impact:medium
  color: 'FBCA04'
  description: Medium business or user impact

- name: impact:low
  color: 'C5DEF5'
  description: Low business or user impact

# ===== SPECIALTY LABELS =====
- name: good-first-issue
  color: '7057FF'
  description: Good for newcomers

- name: help-wanted
  color: '008672'
  description: Extra attention needed

- name: question
  color: 'D876E3'
  description: Further information requested

- name: duplicate
  color: 'CFD3D7'
  description: Duplicate of another issue

- name: wontfix
  color: 'FFFFFF'
  description: Will not be worked on

- name: breaking-change
  color: 'B60205'
  description: Breaking change that requires migration

- name: tech-debt
  color: 'F4C20D'
  description: Technical debt to be addressed

- name: dependencies
  color: '0366D6'
  description: Dependencies update or management

- name: performance
  color: 'FF6B6B'
  description: Performance improvement or issue
